### ISSUE TITLE
compilation PsimagLite/src

### ISSUE THREAD

**Issue by npatel37** [g1257/PsimagLite#1]
[npa@cirth drivers]$ perl make.pl 
Backup of ./Makefile in ./Makefile.bak
make.pl: Make sure to compile PsimagLite/lib first
make.pl: Done writing Makefile
Makefile:162: Makefile.dep: No such file or directory
g++ -O3 -DNDEBUG -Werror -Wall -frecord-gcc-switches   -I../  -I../src -MM integrator.cpp sparseSolverTest.cpp testCRSMatrix.cpp rungeKuttaTest.cpp combineContinuedFraction.cpp continuedFractionCollection.cpp gitrev.cpp jsonExample.cpp range.cpp kernelPolynomial.cpp linearPrediction.cpp options.cpp randomTest.cpp svd.cpp testLapack.cpp threads.cpp testIsClass.cpp testMemResolv1.cpp sumDecomposition.cpp calculator.cpp   > Makefile.dep
g++ -O3 -DNDEBUG -Werror -Wall -frecord-gcc-switches   -I../  -I../src -c integrator.cpp
g++ -O3 -DNDEBUG -o  integrator integrator.o -L../../PsimagLite/lib    -lm  -lpthread -lpsimaglite -llapack -lblas
true integrator
g++ -O3 -DNDEBUG -Werror -Wall -frecord-gcc-switches   -I../  -I../src -c sparseSolverTest.cpp
g++ -O3 -DNDEBUG -o  sparseSolverTest sparseSolverTest.o -L../../PsimagLite/lib    -lm  -lpthread -lpsimaglite -llapack -lblas
true sparseSolverTest
g++ -O3 -DNDEBUG -Werror -Wall -frecord-gcc-switches   -I../  -I../src -c testCRSMatrix.cpp
g++ -O3 -DNDEBUG -o  testCRSMatrix testCRSMatrix.o -L../../PsimagLite/lib    -lm  -lpthread -lpsimaglite -llapack -lblas
true testCRSMatrix
g++ -O3 -DNDEBUG -Werror -Wall -frecord-gcc-switches   -I../  -I../src -c rungeKuttaTest.cpp
g++ -O3 -DNDEBUG -o  rungeKuttaTest rungeKuttaTest.o -L../../PsimagLite/lib    -lm  -lpthread -lpsimaglite -llapack -lblas
true rungeKuttaTest
g++ -O3 -DNDEBUG -Werror -Wall -frecord-gcc-switches   -I../  -I../src -c combineContinuedFraction.cpp
cc1plus: warnings being treated as errors
../src/IoSimple.h: In function ‘int main(int, char**)’:
../src/IoSimple.h:224: error: dereferencing pointer ‘os.99’ does break strict-aliasing rules
../src/IoSimple.h:106: note: initialized from here
make: *** [combineContinuedFraction.o] Error 1

**Comment by g1257** [comment]
This issue should be closed.

https://web.ornl.gov/~gz1/dmrgPlusPlus/faq.html

Why do I get “error: dereferencing pointer” when running make?

The message usually is ../src/IoSimple.h: error: dereferencing pointer does break strict-aliasing rules. This is is a false warning issued by an obsolete version of the gcc compiler. Please delete the -Werror flag from the Makefile and run make again.

**Comment by npatel37** [comment]
Thanks

Nirav
